"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.container = void 0;
const inversify_1 = require("inversify");
const types_1 = require("./types");
const DatabaseService_1 = require("./services/DatabaseService");
const AuthService_1 = require("./services/AuthService");
const UserRepo_1 = require("./repositories/UserRepo");
const ContactRepo_1 = require("./repositories/ContactRepo");
const QuotationRepo_1 = require("./repositories/QuotationRepo");
const BlogRepo_1 = require("./repositories/BlogRepo");
const SpecificationsRepo_1 = require("./repositories/SpecificationsRepo");
const AnalyticsRepo_1 = require("./repositories/AnalyticsRepo");
const AdsRepo_1 = require("./repositories/AdsRepo");
const MailingContactRepo_1 = require("./repositories/MailingContactRepo");
const AuthController_1 = require("./controllers/AuthController");
const CompanyController_1 = require("./controllers/CompanyController");
const BlogController_1 = require("./controllers/BlogController");
const AdsController_1 = require("./controllers/AdsController");
const MailingController_1 = require("./controllers/MailingController");
const container = new inversify_1.Container();
exports.container = container;
container.bind(types_1.TYPES.DatabaseService).to(DatabaseService_1.DatabaseService).inSingletonScope();
container.bind(types_1.TYPES.AuthService).to(AuthService_1.AuthService).inSingletonScope();
container.bind(types_1.TYPES.UserRepo).to(UserRepo_1.UserRepo).inSingletonScope();
container.bind(types_1.TYPES.ContactRepo).to(ContactRepo_1.ContactRepo).inSingletonScope();
container.bind(types_1.TYPES.QuotationRepo).to(QuotationRepo_1.QuotationRepo).inSingletonScope();
container.bind(types_1.TYPES.BlogRepo).to(BlogRepo_1.BlogRepo).inSingletonScope();
container.bind(types_1.TYPES.SpecificationsRepo).to(SpecificationsRepo_1.SpecificationsRepo).inSingletonScope();
container.bind(types_1.TYPES.AnalyticsRepo).to(AnalyticsRepo_1.AnalyticsRepo).inSingletonScope();
container.bind(types_1.TYPES.AdsRepo).to(AdsRepo_1.AdsRepo).inSingletonScope();
container.bind(types_1.TYPES.MailingContactRepo).to(MailingContactRepo_1.MailingContactRepo).inSingletonScope();
container.bind(AuthController_1.AuthController).toSelf();
container.bind(CompanyController_1.CompanyController).toSelf();
container.bind(BlogController_1.BlogController).toSelf();
container.bind(AdsController_1.AdsController).toSelf();
container.bind(MailingController_1.MailingController).toSelf();
//# sourceMappingURL=inversify.config.js.map